confirm_os_window_close 0

font_size 13.0
background_opacity        0.70

font_family      family='Hurmit Nerd Font' postscript_name=HurmitNF-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
window_padding_width 5
tab_bar_style slant
enable_audio_bell no
notify_on_cmd_finish unfocused

foreground         #c3c2c5
background         #0f0b19
cursor             #c3c2c5

active_tab_foreground     #0f0b19
active_tab_background     #c3c2c5
inactive_tab_foreground   #c3c2c5
inactive_tab_background   #0f0b19

active_border_color   #c3c2c5
inactive_border_color #0f0b19
bell_border_color     #9D67B6

color0       #0f0b19
color8       #615a6e
color1       #9D67B6
color9       #9D67B6
color2       #9A66D0
color10      #9A66D0
color3       #E35FDD
color11      #E35FDD
color4       #6584BC
color12      #6584BC
color5       #A993C7
color13      #A993C7
color6       #E6A3E6
color14      #E6A3E6
color7       #c3c2c5
color15      #c3c2c5
